function features_keep = include_nuclear_features(features, flag)

    % depending on the flag:
    switch flag
        
        case 'yes'
            
            % set the stacks that nuclear segmentations are done:
            stacks_with_complete_nuclear_segmentation = [...
                46, 1; ...
                46, 3; ...
                46, 23; ...
                46, 27; ...
                46, 41; ...
                46, 42; ...
                48, 1; ...
                48, 4; ...
                48, 12; ...
                48, 21; ...
                48, 75; ...
                48, 76; ...
                54, 1; ...
                54, 2; ...
                54, 15; ...
                54, 17; ...
                54, 30; ...
                54, 32];
            
            % get number of stacks to keep:
            num_stacks_keep = size(stacks_with_complete_nuclear_segmentation, 1);
            
            % set array to store rows to keep:
            rows = zeros(num_stacks_keep, 1);
            
            % for each stack to keep:
            for i = 1:num_stacks_keep
                
                % get the name of the stack to keep:
                name_stack = sprintf('j%03d_i%03d', stacks_with_complete_nuclear_segmentation(i,1), stacks_with_complete_nuclear_segmentation(i,2));
                
                % get row number to keep:
                [~, rows(i)] = organoids2.utilities.get_structure_results_matching_string(features, 'name_stack', name_stack);
                
            end
            
            % get the 
            features_keep = features(rows);
            
        case 'no'
       
            % remove all nuclear features:
            features_keep = organoids2.analysis.exclude_features_from_data(features, 'nuclei');
            
    end

end