function features_keep = include_nuclear_features(features, flag)

    % depending on the flag:
    switch flag
        
        case 'yes'
            
            % set the stacks that nuclear segmentations are done:
            
            % organoids2:
            stacks_with_complete_nuclear_segmentation = {...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well01_normal_organoids2', 1; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well01_normal_organoids2', 3; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well03_1.6uMSU6668_organoids2', 7; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well04_5.0uMSU6668_organoids2', 3; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well06_400nMlapatinib_organoids2', 1; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_07_09_Organoids_Round_138/well06_400nMlapatinib_organoids2', 2; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_19_Organoids_Round_144/plate1/well01_normal_organoids2', 1; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_19_Organoids_Round_144/plate1/well01_normal_organoids2', 5; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_19_Organoids_Round_144/plate1/well02_DMSO_organoids2', 3; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_19_Organoids_Round_144/plate1/well03_40nMlapatinib_organoids2', 4; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_18_Organoids_Round_144/plate2/well08_30uMidelalisib_organoids2', 4; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/18_09_18_Organoids_Round_144/plate2/well08_30uMidelalisib_organoids2', 5; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well01_normal_organoids2', 1; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well01_normal_organoids2', 2; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well02_DMSO_organoids2', 6; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well02_DMSO_organoids2', 9; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well06_130nMlapatinib_organoids2', 3; ...
                '/Users/laurenbeck/Dropbox (RajLab)/LEB_Organoids/Data/LAUREN_05/Data_Microscopy/Scope_CDB_Core_710/19_03_02_Organoids_Round_154/well06_130nMlapatinib_organoids2', 5; ...
                };
            
            % organoids:
%             stacks_with_complete_nuclear_segmentation = [...
%                 46, 1; ...
%                 46, 3; ...
%                 46, 23; ...
%                 46, 27; ...
%                 46, 41; ...
%                 46, 42; ...
%                 48, 1; ...
%                 48, 4; ...
%                 48, 12; ...
%                 48, 21; ...
%                 48, 75; ...
%                 48, 76; ...
%                 54, 1; ...
%                 54, 2; ...
%                 54, 15; ...
%                 54, 17; ...
%                 54, 30; ...
%                 54, 32];
            
            % get number of stacks to keep:
            num_stacks_keep = size(stacks_with_complete_nuclear_segmentation, 1);
            
            % set array to store rows to keep:
            rows = zeros(num_stacks_keep, 1);
            
            % for each stack to keep:
            for i = 1:num_stacks_keep
                
%                 % get the name of the stack to keep:
%                 name_stack = sprintf('j%03d_i%03d', stacks_with_complete_nuclear_segmentation(i,1), stacks_with_complete_nuclear_segmentation(i,2));
%                 
%                 % get row number to keep:
%                 [~, rows(i)] = organoids2.utilities.get_structure_results_matching_string(features, 'name_stack', name_stack);
                
                % get the organoids from the same folder:
                [features_folder, rows_folder] = organoids2.utilities.get_structure_results_matching_string(features, 'path', stacks_with_complete_nuclear_segmentation{i,1});
                
                % get the organoid to use:
                [~, row_organoid] = organoids2.utilities.get_structure_results_matching_string(features_folder, 'file_name', sprintf('pos%03d', stacks_with_complete_nuclear_segmentation{i,2}));
                
                % save the index of the row to keep:
                rows(i) = rows_folder(row_organoid);
                
            end
            
            % get the 
            features_keep = features(rows);
            
        case 'no'
       
            % remove all nuclear features:
            features_keep = organoids2.analysis.exclude_features_from_data(features, 'nuclei');
            
    end

end